set autocommit off;
delete from
    EMPLOYEES
WHERE
    JOB_ID = 'SA_REP' ;
    
SELECT
    E.EMPLOYEE_ID,
    E.SALARY,
    E.COMMISSION_PCT
FROM
    EMPLOYEES   E
    JOIN DEPARTMENTS D
    USING (DEPARTMENT_ID)
WHERE
    E.JOB_ID ='ST_CLERK'
    AND LOCATION_ID=1500 FOR UPDATE OF E.SALARY
ORDER BY
    E.EMPLOYEE_ID;